---
- hosts: vm
  roles:
    - swap

- hosts: all
  gather_facts: no
  roles:
    - { role: apt_proxy, when: use_apt_proxy }
  tasks:
    - apt: update_cache=yes

- hosts: postgresql
  roles:
    - postgresql


- hosts: application
  handlers:
    - include: roles/sidekiq/handlers/main.yml
  roles:
    - base
    - { role: ruby, tags: ruby }
    - vim
    - webserver

- hosts: sidekiq
  handlers:
    - include: roles/puma/handlers/main.yml
  roles:
    - base
    - ruby
    - { role: sidekiq, tags: sidekiq }

